# Generated by Django 4.1.6 on 2023-02-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseinfo", "0002_alter_course_options_course_unique_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="period",
            options={"ordering": ["period_sequence"]},
        ),
        migrations.AlterModelOptions(
            name="semester",
            options={"ordering": ["year__year", "period__period_sequence"]},
        ),
        migrations.AlterModelOptions(
            name="year",
            options={"ordering": ["year"]},
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("period_sequence",), name="unique_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                fields=("year", "period"), name="unique_semester"
            ),
        ),
        migrations.AddConstraint(
            model_name="year",
            constraint=models.UniqueConstraint(fields=("year",), name="year"),
        ),
    ]
